apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: sglang-pool
  namespace: default
spec:
  selector:
    matchLabels:
      app: sglang
  targetPorts:
  - number: 30000
  appProtocol: http
  endpointPickerRef:
    name: sglang-epp-epp
    kind: Service
    port:
      number: 9002
    failureMode: FailOpen